- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: latest

  - name: Start nginx
    service:
      name: nginx
      state: started

  - name: Create tls certificates
    command: >
      openssl req -new -x509 -nodes -out server.crt -keyout server.key -subj '/CN=localhost' -days 365
    args:
      chdir: /etc/nginx
      creates: /etc/nginx/server.crt
    notify: Restart nginx

  - name: Copy config file
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/conf.d/nginx.conf
    notify: Restart nginx

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
